language: node_js
sudo: false
node_js:
- '6'
- '8'
- '9'
branches:
  except:
    - /^v[0-9]/
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
